"""Protocol invariants; real GPU replay evidence is generated by the bounded driver."""
from copy import deepcopy
import json
from pathlib import Path
from types import SimpleNamespace
import unittest
import numpy as np
import torch
from torch import nn

from yuntapr.contracts.loader import REPO_ROOT, sha256
from yuntapr.models.b0 import B0Model
from yuntapr.training.phase_a_protocol import (PROTOCOL_PATH, EXPECTED_COUNTS, load_protocol, head_pin,
    parameter_groups, adamw, phase_a_lr_for_update, lr_for_update, epoch_permutation,
    state_digest, ValidationSelection, require_engineering_scope, validate_checkpoint_metadata)
from yuntapr.training.phase_a_validation import GlobalValidationAccumulator, grouped_occurrence_metrics


class ProtocolTests(unittest.TestCase):
    def test_exact_approved_values(self):
        c = load_protocol(expected_sha256=sha256(REPO_ROOT / PROTOCOL_PATH))
        self.assertEqual(c["loss"]["occurrence"]["alpha"], .5)
        self.assertEqual(c["loss"]["occurrence"]["gamma"], 2.)
        self.assertEqual(c["optimizer"]["type"], "AdamW")
        self.assertEqual(c["optimizer"]["betas"], [.9, .999])
        self.assertEqual(c["optimizer"]["eps"], 1e-8)
        for key in ("amsgrad", "maximize", "capturable", "differentiable", "foreach", "fused"):
            self.assertIs(c["optimizer"][key], False)
        self.assertEqual(c["batch"], {"train_physical": 2, "gradient_accumulation_steps": 1, "effective": 2, "validation": 8, "drop_last": False})
        self.assertEqual(c["sampling"]["train_count"], 11720)
        self.assertEqual(c["sampling"]["validation_count"], 11727)
        self.assertEqual(c["data_loader"]["num_workers"], 2)
        self.assertEqual(c["data_loader"]["max_temporary_bytes_per_worker"], 734003200)
        self.assertEqual(c["gradient_clipping"]["global_norm"], 5.)
        self.assertEqual(c["reproducibility"]["primary_seed"], 2026)
        self.assertEqual(c["scheduler"]["warmup_lower_bound_resolution"], "RESEARCHER_CONFIRMED_PRESERVE_EXACT_FORMULA")
        self.assertEqual(c["loss"]["quantile"]["epsilon_mono"], 1e-4)
        for key in ("qlog_dtype", "qphysical_dtype", "pinball_dtype"):
            self.assertEqual(c["loss"]["quantile"][key], "float64")
        self.assertEqual(c["loss"]["core"], "L_occ + L_qr")
        self.assertIsNone(c["loss"]["extra_multiplier"])

    def test_head_implementation_pin(self):
        m = B0Model()
        pin = head_pin(m)
        self.assertEqual(pin["occurrence"]["parameters"], 49)
        self.assertEqual(pin["quantile"]["parameters"], 1568)
        m.heads.extra = nn.Identity()
        with self.assertRaisesRegex(ValueError, "Unexpected"):
            head_pin(m)

    def test_exact_disjoint_optimizer_groups(self):
        m = B0Model()
        groups, evidence = parameter_groups(m)
        self.assertEqual(evidence["counts"], EXPECTED_COUNTS)
        ids = [id(p) for group in groups for p in group["params"]]
        self.assertEqual(len(ids), len(set(ids)))
        self.assertEqual(set(ids), {id(p) for p in m.parameters() if p.requires_grad})
        optimizer, _ = adamw(m)
        self.assertEqual([g["weight_decay"] for g in optimizer.param_groups], [1e-4, 0.])
        self.assertIs(optimizer.defaults["foreach"], False)
        self.assertIs(optimizer.defaults["fused"], False)

    def test_unknown_parameter_fails(self):
        m = nn.Sequential(nn.Conv2d(1, 2, 1), nn.Linear(2, 1))
        with self.assertRaisesRegex(ValueError, "Unknown"):
            parameter_groups(m, check_counts=False)

    def test_shared_parameter_fails(self):
        m = nn.Sequential(nn.Conv2d(1, 1, 1), nn.Conv2d(1, 1, 1))
        m[1].weight = m[0].weight
        with self.assertRaises(ValueError):
            parameter_groups(m, check_counts=False)

    def test_schedule_boundaries_no_off_by_one(self):
        f = phase_a_lr_for_update
        self.assertEqual(f(1), 1e-4 / 5860)
        self.assertEqual(f(5860), 1e-4)
        self.assertLess(f(5861), f(5860))
        self.assertEqual(f(293000), 1e-6)
        self.assertLess(f(1), 1e-6)  # explicit researcher resolution, no clamp
        for bad in (0, -1, 293001, 1.0, True):
            with self.assertRaises(ValueError):
                f(bad)

    def test_schedule_full_mathematical_monotonicity(self):
        warmup = np.array([phase_a_lr_for_update(u) for u in range(1, 5861)])
        cosine = np.array([phase_a_lr_for_update(u) for u in range(5861, 293001)])
        self.assertTrue((np.diff(warmup) > 0).all())
        self.assertTrue(((warmup > 0) & (warmup <= 1e-4)).all())
        self.assertTrue((np.diff(cosine) <= 0).all())
        self.assertTrue(((cosine >= 1e-6) & (cosine <= 1e-4)).all())

    def test_finalfit_replay_same_epoch_horizon(self):
        for epoch in (1, 2, 10, 25, 49, 50):
            self.assertEqual(lr_for_update(epoch * 8000, steps_per_epoch=8000), phase_a_lr_for_update(epoch * 5860))
        self.assertGreater(lr_for_update(10 * 8000, steps_per_epoch=8000), 1e-6)

    def test_checkpoint_best_separate_from_early_stop(self):
        s = ValidationSelection()
        self.assertTrue(s.update(1, 1.)["checkpoint_selected"])
        r = s.update(2, .99995)
        self.assertTrue(r["checkpoint_selected"])
        self.assertFalse(r["early_stop_improvement"])
        self.assertEqual(s.early_stop_best, 1.)
        self.assertEqual(s.selected_checkpoint_epoch, 2)
        self.assertFalse(s.update(3, .99995)["checkpoint_selected"])
        self.assertEqual(s.selected_checkpoint_epoch, 2)
        for epoch in range(4, 9):
            self.assertFalse(s.update(epoch, 1.)["stop"])
        self.assertTrue(s.update(9, 1.)["stop"])

    def test_early_stop_strict_boundary_and_reset(self):
        s = ValidationSelection()
        s.update(1, 1.)
        self.assertFalse(s.update(2, 1. - 1e-4)["early_stop_improvement"])
        self.assertTrue(s.update(3, .9998)["early_stop_improvement"])
        self.assertEqual(s.non_improvement_count, 0)
        with self.assertRaises(ValueError):
            s.update(5, .5)

    def test_epoch_shuffle_independent_of_global_rng(self):
        a = epoch_permutation(0)
        torch.rand(300)
        self.assertTrue(torch.equal(a, epoch_permutation(0)))
        self.assertFalse(torch.equal(a, epoch_permutation(1)))
        self.assertTrue(torch.equal(torch.sort(a).values, torch.arange(11720)))

    def test_grouped_ap_and_auc_ties(self):
        result = grouped_occurrence_metrics([.8, .8, .2, .2], [1, 0, 1, 0])
        self.assertEqual(result["Average_Precision"], .5)
        self.assertEqual(result["AUROC"], .5)
        self.assertEqual(result, grouped_occurrence_metrics([.2, .8, .2, .8], [0, 0, 1, 1]))
        self.assertIsNone(grouped_occurrence_metrics([.5], [1])["AUROC"])
        self.assertIsNone(grouped_occurrence_metrics([.5], [0])["Average_Precision"])

    def test_global_validation_raw_numerators_unequal_partition(self):
        y = torch.tensor([0., .1, .2, 3., 8.]).reshape(5, 1, 1, 1)
        z = torch.tensor([-3., -1., 0., 2., 4.]).reshape(5, 1, 1, 1)
        q = (.1001 + torch.arange(32, dtype=torch.float64) * .1).reshape(1, 32, 1, 1).expand(5, -1, -1, -1)
        mask = torch.ones_like(y, dtype=torch.bool)
        def out(sl):
            return SimpleNamespace(rain_logit=z[sl], rain_prob=z[sl].sigmoid(),
                conditional_quantiles_log=q[sl], conditional_quantiles_physical=q[sl].expm1())
        whole, split = GlobalValidationAccumulator(), GlobalValidationAccumulator()
        whole.add(out(slice(None)), y, mask, mask)
        for sl in (slice(0, 1), slice(1, 5)):
            split.add(out(sl), y[sl], mask[sl], mask[sl])
        a, b = whole.report(), split.report()
        self.assertEqual(a["N_valid"], 5)
        self.assertEqual(a["N_rain"], 3)
        self.assertAlmostEqual(a["global_val_core_loss"], b["global_val_core_loss"], places=14)
        self.assertEqual(a["global_val_core_loss"], (a["S_occ"] + a["S_qr"]) / 5)
        self.assertEqual(a["strict_crossing_count"], 0)
        self.assertEqual(a["POD"], "THRESHOLD_NOT_FROZEN")

    def test_state_digest_includes_buffers_and_scalar_optimizer_steps(self):
        a = {"p": torch.tensor([1.]), "step": torch.tensor(2.)}
        self.assertEqual(state_digest(a), state_digest(deepcopy(a)))
        b = deepcopy(a)
        b["step"] += 1
        self.assertNotEqual(state_digest(a), state_digest(b))

    def test_checkpoint_metadata_rejects_identity_and_boundary(self):
        expected = {"scope": "ENGINEERING_ONLY", "checkpoint_kind": "TEMPORARY_PARTIAL_UPDATE_SCHEMA_TEST",
                    "FORMAL_TRAINING_AUTHORIZED": False, "completed_epoch": 0, "global_update": 2,
                    "protocol_sha256": "p", "normalization_artifact_sha256": "n", "scientific_contract_sha256": "s"}
        validate_checkpoint_metadata(expected, expected)
        for key in ("protocol_sha256", "normalization_artifact_sha256", "scientific_contract_sha256", "global_update", "completed_epoch"):
            bad = deepcopy(expected)
            bad[key] = "corrupted"
            with self.assertRaisesRegex(ValueError, "provenance mismatch"):
                validate_checkpoint_metadata(bad, expected)

    def test_no_formal_training_authorization(self):
        c = load_protocol()
        self.assertFalse(c["authorization"]["FORMAL_TRAINING_AUTHORIZED"])
        self.assertFalse(c["authorization"]["B0_FORMAL_TRAINING_STARTED"])
        require_engineering_scope("ENGINEERING_ONLY")
        for scope in (None, "FORMAL", "TRAIN", ""):
            with self.assertRaises(ValueError):
                require_engineering_scope(scope)

    def test_real_replay_and_resume_evidence(self):
        import os
        run = os.environ.get("YUNTAPR_PROTOCOL_DRYRUN_EVIDENCE")
        if not run:
            self.fail("Required real CUDA replay evidence was not supplied")
        run = Path(run)
        replay = json.loads((run / "determinism_comparison.json").read_text(encoding="utf-8"))
        resume = json.loads((run / "resume_checkpoint_test.json").read_text(encoding="utf-8"))
        self.assertTrue(replay["bit_exact_pass"])
        self.assertTrue(resume["exact_pass"])
        self.assertTrue(resume["temporary_checkpoint_deleted"])
        self.assertEqual(replay["run_a_model_state_sha256"], replay["run_b_model_state_sha256"])
        self.assertTrue(resume["optimizer_logically_equivalent"])
        self.assertEqual(resume["global_update"], 3)


if __name__ == "__main__":
    unittest.main()
